/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package dropwizard.on.kotlin

import javax.ws.rs.*
import javax.ws.rs.core.*

@Path("/dok")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
class AppResource {
    @GET
    @Path("{pp}")
    fun get(
        @Context request: Request,
        @Context uriInfo: UriInfo,
        @PathParam("pp") pp: String,
        @DefaultValue("123") @QueryParam("qp") qp: String): Response {


        //val rb = Response.ok(pp.split(","))
        val rb = Response.ok(pp.split(",").map { it.trim() })

        return rb.build()
    }

    @POST
    fun post(input: Something): Response {
        val rb = Response.ok(input)

        return rb.build()
    }

}

class SomethingElse(val field1: String = "", val field2: String = "")

data class Something(val field1: String = "", val field2: String = "")
